"use client"
import './globals.css'
import { StateContext } from '@/context/StateContext' 
import Navigation from '@/layout/navigation'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <StateContext>
            <Navigation />
            {children}
          </StateContext>
        </body>
    </html>
  )
}
